### ISSUE TITLE
Replace constants with strings in position

### ISSUE THREAD

**Issue by talentlessguy** [fergomap/react-element-spinner#1]
Instead of position_enum.CENTER we could just use `position="center"`

it is a cleaner way to set the prop

**Comment by fergomap** [comment]
Hi @talentlessguy , thanks for your comment, I had doubts with this when I first coded this library. You are definetly right! It is already updated and published in v 1.0.2.

**Comment by talentlessguy** [comment]
@fergomap everything else is nice about the component, so I close
