### ISSUE TITLE
A thank you and a suggestion

### ISSUE THREAD

**Issue by arielspalter** [fergomap/react-element-spinner#3]
This library is great! to make it even better I'd suggest to add a text property so one could add text in global position (such as "Loading..." that will appear alongside the spinner ). Other than that, it's super useful. Thank you!

**Comment by fergomap** [comment]
Hi Ariel, thanks for the comment, I am really happy my library helped you. You are totally right, a loading message would be useful. I have just uploaded the v1.0.3 version with this new feature, you can also check the updated [demo](https://fergomap.github.io/react-element-spinner-demo/). I hope this solves the problem, if not please let me know. Thank you!

**Comment by arielspalter** [comment]
That was fast!.. It works like a charm, thank you!

**Comment by fergomap** [comment]
You are welcome, perfect, I close the issue!
