### ISSUE TITLE
Global span style

### ISSUE THREAD

**Issue by merfis** [fergomap/react-element-spinner#5]
In spinner.component.scss there's
`span {
    color: white;
    margin-top: 10px;
    z-index: 1;
}`

This redefines styles for span element globally which leads to undesired side effects when using react-element-spinner in a project with Material-UI Buttons.

**Comment by fergomap** [comment]
Hi @merfis , thanks for your comment. I have just uploaded the version 1.0.4  of react-element-spinner with this problem fixed. You can already try it. I hope this solves your problem, thank you!
